export const ON_CONNECTION_SUCCESS = 'ON_CONNECTION_SUCCESS';
export const ON_CONNECTION_STOP = 'ON_CONNECTION_STOP';
export const ON_CONNECTION_FAIL = 'ON_CONNECTION_FAIL';
export const SET_CONN_PROPERTY = 'SET_CONN_PROPERTY';
export const SET_OUTPUT = 'SET_OUTPUT';

export const ON_TOGGLE = 'ON_TOGGLE';
export const SET_APP_PROPERTY = 'SET_APP_PROPERTY ';
